/** Record message kinds are broader than the existing activity/document link kinds. */
export const CHATTER_RECORD_KINDS: Record<string, string> = {
  customers: "customer",
  sites: "site",
  equipment: "equipment",
  drivers: "driver",
  bids: "bid",
  contacts: "contact",
  products: "product",
  lanes: "lane",
  rates: "rate",
  contracts: "contract",
  opportunities: "opportunity",
  refused_loads: "refused_load",
  incidents: "incident",
  site_assessments: "site_assessment",
  tasks: "task",
  documents: "document",
  requirements: "requirement",
  lost_business: "lost_business",
  corrective_actions: "corrective_action",
  equipment_assignments: "equipment_assignment",
  equipment_leases: "equipment_lease",
  equipment_compliance: "equipment_compliance",
  equipment_technology: "equipment_technology",
  knowledge_articles: "knowledge_article",
};
