// Generated from database foreign keys by scripts/generate-record-links.mjs.
export const DIRECT_RECORD_LINKS: Record<string, Record<string, string[]>> = {
  customers: {
    sites: ["customer_id"],
    equipment: ["current_customer_id"],
    bids: ["customer_id"],
    contacts: ["customer_id"],
    products: ["customer_id"],
    lanes: ["customer_id"],
    rates: ["customer_id"],
    contracts: ["customer_id"],
    opportunities: ["customer_id"],
    refused_loads: ["customer_id"],
    incidents: ["customer_id"],
    lost_business: ["customer_id"],
    equipment_assignments: ["customer_id"],
    equipment_leases: ["customer_id"],
    knowledge_articles: ["customer_id"],
  },
  sites: {
    equipment: ["current_site_id"],
    contacts: ["site_id"],
    lanes: ["destination_site_id", "origin_site_id"],
    rates: ["site_id"],
    opportunities: ["site_id"],
    refused_loads: ["site_id"],
    incidents: ["site_id"],
    site_assessments: ["site_id"],
    lost_business: ["site_id"],
    equipment_assignments: ["site_id"],
    knowledge_articles: ["site_id"],
  },
  opportunities: {
    bids: ["opportunity_id"],
    refused_loads: ["opportunity_id"],
    lost_business: ["opportunity_id"],
  },
  contracts: { rates: ["contract_id"], equipment_leases: ["contract_id"] },
  lanes: {
    rates: ["lane_id"],
    refused_loads: ["lane_id"],
    incidents: ["lane_id"],
    lost_business: ["lane_id"],
    equipment_assignments: ["lane_id"],
  },
  products: {
    rates: ["product_id"],
    refused_loads: ["product_id"],
    lost_business: ["product_id"],
    equipment_assignments: ["product_id"],
  },
  bids: { refused_loads: ["bid_id"] },
  contacts: { refused_loads: ["contact_id"] },
  equipment: {
    refused_loads: ["equipment_id"],
    incidents: ["equipment_id"],
    equipment_assignments: ["equipment_id"],
    equipment_leases: ["equipment_id"],
    equipment_compliance: ["equipment_id"],
    equipment_technology: ["equipment_id"],
  },
  rates: { refused_loads: ["rate_id"] },
  refused_loads: { lost_business: ["refused_load_id"] },
  incidents: { corrective_actions: ["incident_id"] },
};
