/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedCommandCenterRouteImport } from './routes/_authenticated/command-center'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedBidsIndexRouteImport } from './routes/_authenticated/bids.index'
import { Route as AuthenticatedCustomersIndexRouteImport } from './routes/_authenticated/customers.index'
import { Route as AuthenticatedCustomersCustomerIdRouteImport } from './routes/_authenticated/customers.$customerId'
import { Route as AuthenticatedEquipmentIndexRouteImport } from './routes/_authenticated/equipment.index'
import { Route as AuthenticatedEquipmentEquipmentIdRouteImport } from './routes/_authenticated/equipment.$equipmentId'
import { Route as AuthenticatedKnowledgeIndexRouteImport } from './routes/_authenticated/knowledge.index'
import { Route as AuthenticatedLostLoadsIndexRouteImport } from './routes/_authenticated/lost-loads.index'
import { Route as AuthenticatedLostLoadsNewRouteImport } from './routes/_authenticated/lost-loads.new'
import { Route as AuthenticatedRefusedLoadsIndexRouteImport } from './routes/_authenticated/refused-loads.index'
import { Route as AuthenticatedReportsIndexRouteImport } from './routes/_authenticated/reports.index'
import { Route as AuthenticatedSafetyIndexRouteImport } from './routes/_authenticated/safety.index'
import { Route as AuthenticatedSalesIndexRouteImport } from './routes/_authenticated/sales.index'
import { Route as AuthenticatedSitesIndexRouteImport } from './routes/_authenticated/sites.index'
import { Route as AuthenticatedSitesSiteIdRouteImport } from './routes/_authenticated/sites.$siteId'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCommandCenterRoute =
  AuthenticatedCommandCenterRouteImport.update({
    id: '/command-center',
    path: '/command-center',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBidsIndexRoute = AuthenticatedBidsIndexRouteImport.update({
  id: '/bids/',
  path: '/bids/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomersIndexRoute =
  AuthenticatedCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomersCustomerIdRoute =
  AuthenticatedCustomersCustomerIdRouteImport.update({
    id: '/customers/$customerId',
    path: '/customers/$customerId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEquipmentIndexRoute =
  AuthenticatedEquipmentIndexRouteImport.update({
    id: '/equipment/',
    path: '/equipment/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEquipmentEquipmentIdRoute =
  AuthenticatedEquipmentEquipmentIdRouteImport.update({
    id: '/equipment/$equipmentId',
    path: '/equipment/$equipmentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKnowledgeIndexRoute =
  AuthenticatedKnowledgeIndexRouteImport.update({
    id: '/knowledge/',
    path: '/knowledge/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLostLoadsIndexRoute =
  AuthenticatedLostLoadsIndexRouteImport.update({
    id: '/lost-loads/',
    path: '/lost-loads/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLostLoadsNewRoute =
  AuthenticatedLostLoadsNewRouteImport.update({
    id: '/lost-loads/new',
    path: '/lost-loads/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRefusedLoadsIndexRoute =
  AuthenticatedRefusedLoadsIndexRouteImport.update({
    id: '/refused-loads/',
    path: '/refused-loads/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSafetyIndexRoute =
  AuthenticatedSafetyIndexRouteImport.update({
    id: '/safety/',
    path: '/safety/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalesIndexRoute = AuthenticatedSalesIndexRouteImport.update({
  id: '/sales/',
  path: '/sales/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSitesIndexRoute = AuthenticatedSitesIndexRouteImport.update({
  id: '/sites/',
  path: '/sites/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSitesSiteIdRoute =
  AuthenticatedSitesSiteIdRouteImport.update({
    id: '/sites/$siteId',
    path: '/sites/$siteId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/command-center': typeof AuthenticatedCommandCenterRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/equipment/$equipmentId': typeof AuthenticatedEquipmentEquipmentIdRoute
  '/lost-loads/new': typeof AuthenticatedLostLoadsNewRoute
  '/sites/$siteId': typeof AuthenticatedSitesSiteIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/bids/': typeof AuthenticatedBidsIndexRoute
  '/customers/': typeof AuthenticatedCustomersIndexRoute
  '/equipment/': typeof AuthenticatedEquipmentIndexRoute
  '/knowledge/': typeof AuthenticatedKnowledgeIndexRoute
  '/lost-loads/': typeof AuthenticatedLostLoadsIndexRoute
  '/refused-loads/': typeof AuthenticatedRefusedLoadsIndexRoute
  '/reports/': typeof AuthenticatedReportsIndexRoute
  '/safety/': typeof AuthenticatedSafetyIndexRoute
  '/sales/': typeof AuthenticatedSalesIndexRoute
  '/sites/': typeof AuthenticatedSitesIndexRoute
  '/tasks/': typeof AuthenticatedTasksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/command-center': typeof AuthenticatedCommandCenterRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/equipment/$equipmentId': typeof AuthenticatedEquipmentEquipmentIdRoute
  '/lost-loads/new': typeof AuthenticatedLostLoadsNewRoute
  '/sites/$siteId': typeof AuthenticatedSitesSiteIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/bids': typeof AuthenticatedBidsIndexRoute
  '/customers': typeof AuthenticatedCustomersIndexRoute
  '/equipment': typeof AuthenticatedEquipmentIndexRoute
  '/knowledge': typeof AuthenticatedKnowledgeIndexRoute
  '/lost-loads': typeof AuthenticatedLostLoadsIndexRoute
  '/refused-loads': typeof AuthenticatedRefusedLoadsIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/safety': typeof AuthenticatedSafetyIndexRoute
  '/sales': typeof AuthenticatedSalesIndexRoute
  '/sites': typeof AuthenticatedSitesIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/command-center': typeof AuthenticatedCommandCenterRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/_authenticated/equipment/$equipmentId': typeof AuthenticatedEquipmentEquipmentIdRoute
  '/_authenticated/lost-loads/new': typeof AuthenticatedLostLoadsNewRoute
  '/_authenticated/sites/$siteId': typeof AuthenticatedSitesSiteIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/bids/': typeof AuthenticatedBidsIndexRoute
  '/_authenticated/customers/': typeof AuthenticatedCustomersIndexRoute
  '/_authenticated/equipment/': typeof AuthenticatedEquipmentIndexRoute
  '/_authenticated/knowledge/': typeof AuthenticatedKnowledgeIndexRoute
  '/_authenticated/lost-loads/': typeof AuthenticatedLostLoadsIndexRoute
  '/_authenticated/refused-loads/': typeof AuthenticatedRefusedLoadsIndexRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
  '/_authenticated/safety/': typeof AuthenticatedSafetyIndexRoute
  '/_authenticated/sales/': typeof AuthenticatedSalesIndexRoute
  '/_authenticated/sites/': typeof AuthenticatedSitesIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/command-center'
    | '/profile'
    | '/settings'
    | '/customers/$customerId'
    | '/equipment/$equipmentId'
    | '/lost-loads/new'
    | '/sites/$siteId'
    | '/admin/'
    | '/bids/'
    | '/customers/'
    | '/equipment/'
    | '/knowledge/'
    | '/lost-loads/'
    | '/refused-loads/'
    | '/reports/'
    | '/safety/'
    | '/sales/'
    | '/sites/'
    | '/tasks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/command-center'
    | '/profile'
    | '/settings'
    | '/customers/$customerId'
    | '/equipment/$equipmentId'
    | '/lost-loads/new'
    | '/sites/$siteId'
    | '/admin'
    | '/bids'
    | '/customers'
    | '/equipment'
    | '/knowledge'
    | '/lost-loads'
    | '/refused-loads'
    | '/reports'
    | '/safety'
    | '/sales'
    | '/sites'
    | '/tasks'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/command-center'
    | '/_authenticated/profile'
    | '/_authenticated/settings'
    | '/_authenticated/customers/$customerId'
    | '/_authenticated/equipment/$equipmentId'
    | '/_authenticated/lost-loads/new'
    | '/_authenticated/sites/$siteId'
    | '/_authenticated/admin/'
    | '/_authenticated/bids/'
    | '/_authenticated/customers/'
    | '/_authenticated/equipment/'
    | '/_authenticated/knowledge/'
    | '/_authenticated/lost-loads/'
    | '/_authenticated/refused-loads/'
    | '/_authenticated/reports/'
    | '/_authenticated/safety/'
    | '/_authenticated/sales/'
    | '/_authenticated/sites/'
    | '/_authenticated/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/command-center': {
      id: '/_authenticated/command-center'
      path: '/command-center'
      fullPath: '/command-center'
      preLoaderRoute: typeof AuthenticatedCommandCenterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bids/': {
      id: '/_authenticated/bids/'
      path: '/bids'
      fullPath: '/bids/'
      preLoaderRoute: typeof AuthenticatedBidsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers/': {
      id: '/_authenticated/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AuthenticatedCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers/$customerId': {
      id: '/_authenticated/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof AuthenticatedCustomersCustomerIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipment/': {
      id: '/_authenticated/equipment/'
      path: '/equipment'
      fullPath: '/equipment/'
      preLoaderRoute: typeof AuthenticatedEquipmentIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipment/$equipmentId': {
      id: '/_authenticated/equipment/$equipmentId'
      path: '/equipment/$equipmentId'
      fullPath: '/equipment/$equipmentId'
      preLoaderRoute: typeof AuthenticatedEquipmentEquipmentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/knowledge/': {
      id: '/_authenticated/knowledge/'
      path: '/knowledge'
      fullPath: '/knowledge/'
      preLoaderRoute: typeof AuthenticatedKnowledgeIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lost-loads/': {
      id: '/_authenticated/lost-loads/'
      path: '/lost-loads'
      fullPath: '/lost-loads/'
      preLoaderRoute: typeof AuthenticatedLostLoadsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lost-loads/new': {
      id: '/_authenticated/lost-loads/new'
      path: '/lost-loads/new'
      fullPath: '/lost-loads/new'
      preLoaderRoute: typeof AuthenticatedLostLoadsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/refused-loads/': {
      id: '/_authenticated/refused-loads/'
      path: '/refused-loads'
      fullPath: '/refused-loads/'
      preLoaderRoute: typeof AuthenticatedRefusedLoadsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/safety/': {
      id: '/_authenticated/safety/'
      path: '/safety'
      fullPath: '/safety/'
      preLoaderRoute: typeof AuthenticatedSafetyIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales/': {
      id: '/_authenticated/sales/'
      path: '/sales'
      fullPath: '/sales/'
      preLoaderRoute: typeof AuthenticatedSalesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sites/': {
      id: '/_authenticated/sites/'
      path: '/sites'
      fullPath: '/sites/'
      preLoaderRoute: typeof AuthenticatedSitesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sites/$siteId': {
      id: '/_authenticated/sites/$siteId'
      path: '/sites/$siteId'
      fullPath: '/sites/$siteId'
      preLoaderRoute: typeof AuthenticatedSitesSiteIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCommandCenterRoute: typeof AuthenticatedCommandCenterRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedCustomersCustomerIdRoute: typeof AuthenticatedCustomersCustomerIdRoute
  AuthenticatedEquipmentEquipmentIdRoute: typeof AuthenticatedEquipmentEquipmentIdRoute
  AuthenticatedLostLoadsNewRoute: typeof AuthenticatedLostLoadsNewRoute
  AuthenticatedSitesSiteIdRoute: typeof AuthenticatedSitesSiteIdRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedBidsIndexRoute: typeof AuthenticatedBidsIndexRoute
  AuthenticatedCustomersIndexRoute: typeof AuthenticatedCustomersIndexRoute
  AuthenticatedEquipmentIndexRoute: typeof AuthenticatedEquipmentIndexRoute
  AuthenticatedKnowledgeIndexRoute: typeof AuthenticatedKnowledgeIndexRoute
  AuthenticatedLostLoadsIndexRoute: typeof AuthenticatedLostLoadsIndexRoute
  AuthenticatedRefusedLoadsIndexRoute: typeof AuthenticatedRefusedLoadsIndexRoute
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
  AuthenticatedSafetyIndexRoute: typeof AuthenticatedSafetyIndexRoute
  AuthenticatedSalesIndexRoute: typeof AuthenticatedSalesIndexRoute
  AuthenticatedSitesIndexRoute: typeof AuthenticatedSitesIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCommandCenterRoute: AuthenticatedCommandCenterRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedCustomersCustomerIdRoute: AuthenticatedCustomersCustomerIdRoute,
  AuthenticatedEquipmentEquipmentIdRoute:
    AuthenticatedEquipmentEquipmentIdRoute,
  AuthenticatedLostLoadsNewRoute: AuthenticatedLostLoadsNewRoute,
  AuthenticatedSitesSiteIdRoute: AuthenticatedSitesSiteIdRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedBidsIndexRoute: AuthenticatedBidsIndexRoute,
  AuthenticatedCustomersIndexRoute: AuthenticatedCustomersIndexRoute,
  AuthenticatedEquipmentIndexRoute: AuthenticatedEquipmentIndexRoute,
  AuthenticatedKnowledgeIndexRoute: AuthenticatedKnowledgeIndexRoute,
  AuthenticatedLostLoadsIndexRoute: AuthenticatedLostLoadsIndexRoute,
  AuthenticatedRefusedLoadsIndexRoute: AuthenticatedRefusedLoadsIndexRoute,
  AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
  AuthenticatedSafetyIndexRoute: AuthenticatedSafetyIndexRoute,
  AuthenticatedSalesIndexRoute: AuthenticatedSalesIndexRoute,
  AuthenticatedSitesIndexRoute: AuthenticatedSitesIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
